# F5TTS_v1_Base | E2TTS_Base
model = "F5TTS_v1_Base"

ref_audio = "infer/examples/basic/basic_ref_zh.wav"
ref_text = "对，这就是我，万人敬仰的太乙真人。"

# ref_audio = "infer/examples/basic/basic_ref_en.wav"
# If an empty "", transcribes the reference audio automatically.
# ref_text = "Some call me nature, others call me mother nature."
gen_text = "今天天气真好，适合出去走走"
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"
output_file = "infer_cli_basic.wav"

ckpt_file = "ckpts/F5TTS_v1_Base/model_1250000.safetensors"
vocab_file = "ckpts/F5TTS_v1_Base/vocab.txt"
